### ISSUE TITLE
Where is the code of the plugin Xi/Tweaks located on the internet?

### ISSUE THREAD

**Issue by ralf3u** [xiota/geany-tab-style#4]
The code as zip-file of the plugin `Preview` can be found when visiting https://github.com/xiota/geany-preview and by clicking there on the green button `Code`.
But I don't know where to find the code as zip-file of the plugin Xi/Tweaks.

**Comment by xiota** [comment]
That plugin is not in a repo yet.  I'm planning to do make one eventually.  The code can be downloaded from the PPA (have to click around to find link).  Looks like Ubuntu 24.10 was released earlier this month, so have to update.

**Comment by ralf3u** [comment]
> Looks like Ubuntu 24.10 was released earlier this month, so have to update.

I don't know if an update is necessary. I upgraded from Lubuntu 24.04 to Lubuntu 24.10 some days ago. The plugins Preview, Lua Scripts and Xi/Tweaks are working fine.

**Comment by ralf3u** [comment]
>The code can be downloaded from the PPA (have to click around to find link).

I found this:
https://launchpad.net/~xiota/+archive/ubuntu/geany-plugins
On that webpage I found:
geany-plugin-xi-tweaks 	1:0.0.0-r32.g9900a17-1[...]ppa1[...]ubuntu22.04
But I don't know how to download the code.

**Comment by xiota** [comment]
Click link "View package details".  Click the triangle expander next to the package you're interested in.  There should be links under heading "Package files".  Source code has extension `.orig.tar.xz`.  The `.debian.tar.xz` files are used for packaging.  The `.deb` files can be used directly if you don't want to install the PPA.

**Comment by ralf3u** [comment]
>Click link "View package details". Click the triangle expander next to the package you're interested in. There should be links under heading "Package files". Source code has extension .orig.tar.xz. The .debian.tar.xz files are used for packaging. The .deb files can be used directly if you don't want to install the PPA.

It worked for me. Thank you for your help.

**Comment by ralf3u** [comment]
>The .deb files can be used directly if you don't want to install the PPA.

I tried to install the deb with:
sudo apt install BLABLA.deb

The problem is that in Geany I can't see the plugin Xi/Tweaks in the plugin manager.
What did I make wrong?

**Comment by ralf3u** [comment]
>The problem is that in Geany I can't see the plugin Xi/Tweaks in the plugin manager.
What did I make wrong?

Maybe it is because I installed the wrong package, namely tweaks-ui-24.04 instead of xi-tweaks on a Lubuntu 24.10.
I will install Lubuntu 24.04 and then I will install deb of xi-tweaks-24.04 with sudo apt install full-path.deb.
I will mention if that works for me.

**Comment by xiota** [comment]
PPA is out of date.  I didn't update it for Ubuntu 24.10... and now 25.04 is around the corner.

**Comment by ralf3u** [comment]
>PPA is out of date. I didn't update it for Ubuntu 24.10... and now 25.04 is around the corner.

I don't need an update for Lubuntu 24.10 because 25.04 is indeed around the corner.  But something is strange: I upgraded Lubuntu 24.04 to Lubuntu 24.10. With the command lsb_release -a I can see that I use 24.10.  And in Lubuntu 24.10 everything is running like Preview and Xi/Tweaks.

**Comment by ralf3u** [comment]
>I will install Lubuntu 24.04 and then I will install deb of xi-tweaks-24.04 with sudo apt install full-path.deb.
I will mention if that works for me.

It works for me.

FYI, out of curiosity I installed also Tweaks-UI after having installed and tested preview and xi/tweaks. In the plugin manager I made a checkbox next to Tweaks-UI, and then Geany crashed. I tried it again. But Geany crashed again.

**Comment by xiota** [comment]
> I upgraded Lubuntu... everything is running...

You're still using the 24.04 packages.  When dependencies don't have major changes, old packages can continue working.

> Tweaks-UI ... crashed...

Could be the LTO (link-time optimization) issue that was causing the main preview plugin to crash a while ago.  The setting is supposed to improve runtime performance, but in some cases causes errors.

**Comment by xiota** [comment]
I triggered rebuilds on PPA for 24.10.  Also, rebuilt tweaks-ui plugin without LTO, which might prevent the crash.

**Comment by ralf3u** [comment]
>I triggered rebuilds on PPA for 24.10. Also, rebuilt tweaks-ui plugin without LTO, which might prevent the crash.

In Lubuntu 24.10 Tweaks-ui crashed.

**Comment by xiota** [comment]
When you run geany in terminal, are there any error messages?

**Comment by ralf3u** [comment]
>When you run geany in terminal, are there any error messages?

No. But when I open the plugin manager this is the content of the terminal:
```

(geany:2982): Gtk-WARNING **: 22:19:34.999: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(geany:2982): Gtk-WARNING **: 22:19:34.999: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node entry, owner GtkEntry)

(geany:2982): Gtk-WARNING **: 22:19:34.999: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(geany:2982): Gtk-WARNING **: 22:19:34.999: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(geany:2982): Gtk-WARNING **: 22:19:35.000: Negative content width -9 (allocation 1, extents 5x5) while allocating gadget (node scrollbar, owner GtkScrollbar)

(geany:2982): Gtk-CRITICAL **: 22:19:35.000: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(geany:2982): Gtk-WARNING **: 22:19:35.000: gtk_widget_size_allocate(): attempt to allocate widget with width 17 and height -29

(geany:2982): Gtk-WARNING **: 22:19:35.001: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node scrollbar, owner GtkScrollbar)
```
And when I activate the plugin Tweaks-UI:
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
Aborted (core dumped)
````
And then Geany is crashing.

**Comment by xiota** [comment]
Probably caused by a compiler flag `_GLIBCXX_ASSERTIONS`.  Will have to research how to remove it.

I might have an indexing error somewhere, but my understanding is the checks are hyper-sensitive and may trigger for non-errors.
